### ISSUE TITLE
cwk_path_get_relative segfaulted

### ISSUE THREAD

**Issue by winterland1989** [likle/cwalk#17]
`cwk_path_get_relative` is buggy if:

* two input path are not the same type, e.g. `cwk_path_get_relative("/foo", "./bar", ...)`, in this case `cwk_path_get_relative` return garbage result.
* the second input path is a root, e.g. `cwk_path_get_relative("...", "/", ...)`, in this case `cwk_path_get_relative` segfaulted.

**Comment by likle** [comment]
Hi @winterland1989 ! Thanks for submitting this, I will have a look at it.

**Comment by likle** [comment]
What result would you expect in the first case? "./bar"?

**Comment by winterland1989** [comment]
After reading the source, I found in the first case the return value is 0, so it's not cwalk's problem, maybe writing a `NULL` byte to the buffer? Anyway please add some documents about this behavior.

The second case is definitely is a bug.

**Comment by likle** [comment]
Absolutely, I can reproduce it and will fix it as soon as possible.

**Comment by likle** [comment]
As the documentation says, the result should always be null terminated. So both cases were bugs and have been fixed on the master branch. Please let me know if something doesnt work as expected!

**Comment by winterland1989** [comment]
Thank you! I have tested the new code, there is still a problem I think: `cwk_path_get_relative("./foo", "/bar", ...)` doesn't return 0(which i think it should).

**Comment by likle** [comment]
Oh no! you are right - I fixed that as well.
